FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    sqlite3 \
    libsqlite3-dev \
    build-essential

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["sh", "./build_files.sh"]
